### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#101]
Guys,
I have been naming files .h and .cc even though they do contain a little CUDA code.
This is partly because my emacs setup doesn't auto-format CUDA right, which I know is a bit lazy.
I notice Meixu in his new PR is naming the test files .cu.
I think we should be consistent here.  Do you guys think it was a mistake to start naming 
files containing CUDA .h and .cc?  (they are mostly C++ though).  And do you think we should make
the test files .cc as well?  How does this interact with CMake?

**Comment by qindazhu** [comment]
BTW, It seems to me that we don't need to include cuda related head files if we name files with `.cu`. If we want to name with `.cc`, should we add those head files manually or do this by CMake? Currently I prefer to name with `.cu` as we definitely will mix host and device code in most of files (since we use `if-cpu-else-gpu` convention instead of inheritance or template, we can not split device code to separate file). I guess there is only few pure `.cc` files in our code finally.

**Comment by danpovey** [comment]
MM.  OK, let me think about it more, we'll see if there are other comments.

**Comment by csukuangfj** [comment]
>  we can not split device code to separate file

According to <https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#using-separate-compilation-in-cuda>,
we can split device code across multiple files since cuda 5.0. There is even a flag `CUDA_SEPARABLE_COMPILATION` in CMake to support this.

Maybe someone with much cuda programming experience can suggest how to organize the source files.

**Comment by qindazhu** [comment]
By saying `if-cpu-else-gpu` I mean we implement cpu and gpu version of an algorithm in one function with if-else (instead of using template or inheritantce), so there may be nothing to do with `separate-compilation`.

**Comment by jtrmal** [comment]
IIRC, the cu files contain kernels and should be passed to nvcc and CMake
will do this automagically -- it's possible do enforce this even with cc
files, but it's more work.
IMO preferable is have the kernels in cu files and the calls of the kernels
in cc files.
y.

**Comment by songmeixu** [comment]
I investigating it for hours. Here is my thought:

- The separable compilation has a relation with the file organizations and extensions, but there are ways to hack, as IE. the extension is just a part of filename. But the way to hack it, it's not elegant and got deprecated by CMake (`FindCUDA` is required which is deprecated at CMake-3.10.). CMake community pay serious attention to cuda issues, and now there is a FindCUDAToolkit which make thing much easier since cmake-3.17/18 (CUDA_ARCHITECTURES is introduced at 3.18). Next, to be detailed, I would explain something as far as I know.

- Allows CUDA code to call device functions implemented in other translation units (.cu, .cc if config)

- CMake 3.8 is capable of separable compilation and device linking. Device linking of static libraries occurs when they are consumed by a shared library or executable.

- It makes .cu codes more flexible to be able to call from other .cu. Without it, and as the current default mode, the whole compilation is utilized. In Which, .cu codes only know each other during the final link. It's fine if just .cc call them, as they are independent. But if one wants to call from .cu, it wouldn't pass compilation of nvcc.

- To achieve this work, actually, a static link done by nvcc (called dlink) is introduced between "the nvcc compilation" and "the final link stage of the host c++". And this dlink degrades performance, especially for multi-arch PTX codes which need compilations for the target device in run-time. While as to the default whole mode, it does nothing at dlink stage (yes, it's kept even for the whole mode).

- Though separable compilation is flexible, it comes with unavoidable and significant time loss.
And though the whole compilation restricts the .cu callable, there is even not a needing here usually. The kernel is the very base code with cuda-threads running, it's some unexpected to call another entity from other .cu. From the days before cuda-5 to days it's used as the default, it verifies itself.

- IMO, the whole compilation loosens the restriction about file extension, as the job to resolve confusion about the mix of cu/c++ code files, is passed to the build system (CMake) or device/host compiler themself.

- Above all, as the decision that nvidia has made, the whole mode is the default and preferred.

**Comment by songmeixu** [comment]
But for the whole mode, it has some problems need notice.

As it makes mixture compilation farther to the host cpp part. Some host cpp compilation flags are not in the same form.

There is a function to deal with the flag issue:
```cmake
function(CUDA_CONVERT_FLAGS EXISTING_TARGET)
    get_property(old_flags TARGET ${EXISTING_TARGET} PROPERTY INTERFACE_COMPILE_OPTIONS)
    if(NOT "${old_flags}" STREQUAL "")
        string(REPLACE ";" "," CUDA_flags "${old_flags}")
        set_property(TARGET ${EXISTING_TARGET} PROPERTY INTERFACE_COMPILE_OPTIONS
		"$<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CXX>>:${old_flags}>$<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CUDA>>:-Xcompiler=${CUDA_flags}>"
            )
    endif()
endfunction()
```

IDK if it has well handled by FindCUDAToolkit already, as IIRC it says one need do nothing for cuda after import it.

**Comment by songmeixu** [comment]
But for the whole mode, it has some problems need notice.

As it makes mixture compilation farther to the host cpp part. Some host cpp compilation flags are not in the same form.

There is a function to deal with the flag issue:
```cmake
function(CUDA_CONVERT_FLAGS EXISTING_TARGET)
    get_property(old_flags TARGET ${EXISTING_TARGET} PROPERTY INTERFACE_COMPILE_OPTIONS)
    if(NOT "${old_flags}" STREQUAL "")
        string(REPLACE ";" "," CUDA_flags "${old_flags}")
        set_property(TARGET ${EXISTING_TARGET} PROPERTY INTERFACE_COMPILE_OPTIONS
		"$<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CXX>>:${old_flags}>$<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CUDA>>:-Xcompiler=${CUDA_flags}>"
            )
    endif()
endfunction()
```

IDK if it has well handled by FindCUDAToolkit already, as IIRC it says one need do nothing for cuda after import it.

**Comment by songmeixu** [comment]
As I said, this separable/whole compilation doesn't doom an exact form about files organization and extension. But to be in normal convention and to be clear,

I suggest,

To the source files:
- .cc for cpp codes
- .cu for cuda kernel/functions (Someone use .curnel exclusible for kernels implementation, but it's not a convention and I think it's fine to put the implementation of cuda-related API or its needing kernel all in a same .cu file).

To the header files, as .cuh or .h header are not distinguished by cuda. IDK a reason about how to choose. But for clarity, I think .cuh wins, as .cu has been utilized. Only the header with cuda keywords("__device__. __global__") faces this problem, and it's only recognized by cuda, to be called .cuh is lossless.

**Comment by songmeixu** [comment]
As to the way about how to get cpu/gpu kernels both presented. IMO it's not a reason to follow the cpp style. 

As to the template or lambda, which is a mixture cpu/gpu kernel, IDK what's the key difference with separated ones, but i think cuda is compatible with both. In fact, cuda support cpp std till to the latest, though not all features are support. The way we used is unsupported (IDK)?  Please tell about it.

**Comment by songmeixu** [comment]
PS, use .h for cuda header doesn't require the needing cuda headers included, it's just to make IDE intelligence happy. We can define some keywords even with nonsense to get the intelligent indexing/parsing work as included the right cuda headers.
