### ISSUE TITLE
Compile LG: When arpa is large, an error occurs

### ISSUE THREAD

**Issue by jingyu1220** [k2-fsa/k2#1233]
the error is :
Check failed: state_index_c + 2 == arc_indexes_.size() (-1909392433 vs. 2385574863)

**Comment by csukuangfj** [comment]
How large is your LG?

If it is too large, we suggest that you prune your G before composing it with L.

**Comment by jingyu1220** [comment]
The G.fst.txt is 68G. As we want to use a large G to get better performance.

**Comment by jingyu1220** [comment]
> How large is your LG?
> 
> If it is too large, we suggest that you prune your G before composing it with L.

**Comment by jingyu1220** [comment]
This error is like an array out of bounds problem

**Comment by danpovey** [comment]
Likely the issue is that after composing with L, some of the indexes go outside the range of int32.  I believe we may have some examples of using OpenFST instead of k2 to compile decoding graphs, as it has slightly larger maximum limits (although there is also an int32 limitation, just with some differences of implementation).

**Comment by danpovey** [comment]
Wait, 68G??  You sure you don't mean 68M?  68G is way way out of bounds.
Normally when people want a good LM they rely on neural language models.
