### ISSUE TITLE
CMake issues

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#186]
Can someone please check that the makefile setup avoids doing extra work whenever possible?
Scenarios like:
  rerun `cmake ..`: should not re-download stuff or recompile stuff it's already compiled, if possible?
  change one small piece of source: should not recompile everything.
  change one test program: is it possible to only recompile that one program?

**Comment by csukuangfj** [comment]
> rerun cmake ..: should not re-download stuff or recompile stuff it's already compiled, if possible?

Yes, the current setup already achieves this goal.

----

> change one small piece of source: should not recompile everything.

If you only change a `.cu` file, cmake will ensure that only the changed `.cu` file is re-compiled and re-linked.
But the problem is that K2 contains lots of templates which are `.h` files. I guess what you have modified is
a header file, so there are lots of recompilations. I am afraid the re-compilation cannot be avoided for the current
setup.

One approach is to use explicit instantiation, e.g., move the implementations to `.cu` files and leave only
template declarations in the header files. As the supported data types are known, I think this is feasible.


---

> change one test program: is it possible to only recompile that one program?

Yes, all test programs are `.cu` files and I think there are no re-compilations of other files in the current setup.

**Comment by csukuangfj** [comment]
By restricting

https://github.com/k2-fsa/k2/blob/68a5d00f8af59f56f4ce24776a48d32b616edef1/CMakeLists.txt#L89

`K2_COMPUTE_ARCHS` to support only one `arch` can decrease compile as well as link time.

**Comment by danpovey** [comment]
Mm.  Hard to know which one though?  Perhaps for development we could
figure out which one and just manually edit that file?

**Comment by csukuangfj** [comment]
The log message of `cmake ..` will show the architecture of your GPU. We can change it locally.
