### ISSUE TITLE
Bugs in Append of RaggedShape

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#222]
The following code
https://github.com/k2-fsa/k2/blob/daf77cf68094a6f6d0ae4bcb4664ea2f64ff67c2/k2/csrc/fsa_algo_test.cu#L78-L82
will abort the program due to the invocation of 
https://github.com/k2-fsa/k2/blob/cc752e5a8f3ccca80c2f3d6bc546a92a5ae92243/k2/csrc/ragged.cu#L875

---

I've found two problems in the code:

(1)

https://github.com/k2-fsa/k2/blob/cc752e5a8f3ccca80c2f3d6bc546a92a5ae92243/k2/csrc/ragged.cu#L888-L893

`tot_sizes_out` does not include the last axis, e.g, the number of arcs in an fsa (`offsets` have `num_axes + 1` rows.)

(2)
https://github.com/k2-fsa/k2/blob/cc752e5a8f3ccca80c2f3d6bc546a92a5ae92243/k2/csrc/ragged.cu#L895-L897

https://github.com/k2-fsa/k2/blob/cc752e5a8f3ccca80c2f3d6bc546a92a5ae92243/k2/csrc/ragged.cu#L813-L817

It is invalid to call `ans.Populate();` since it does not contain valid data, only the shapes are allocated.

**Comment by qindazhu** [comment]
`Append/Stack/Renumbering` have not been fixed and tested. I'll do this in the following two days. Please ignore this for now, Thanks!

**Comment by danpovey** [comment]
Thanks, guys!  You are making incredible progress.  I am not feeling as
energetic as I'd like to so I haven't been coding as much as you have, but
I am doing something (right now writing the GPU-based top-sorting code).

**Comment by qindazhu** [comment]
> tot_sizes_out does not include the last axis, e.g, the number of arcs in an fsa (offsets have num_axes + 1 rows.)

Noted the first rows of `offsets` is `0, 1,2,3...` (i.e. exclusive-sum of the number of shapes), so `tot_sizes` here is right, but we should do `tot_sizes_out[axis] = offsets_acc(axis + 1, num_srcs);`.

> It is invalid to call ans.Populate(); since it does not contain valid data, only the shapes are allocated.

It's safe to call `RaggedShape.Populate` as long as the shapes are allocated, actually it will do nothing as we have checked this in `RowId()`
https://github.com/k2-fsa/k2/blob/0d57532b53b63a67ce98a5179035d696c0f64f02/k2/csrc/ragged.cu#L158

Anyway, bugs in `Append` have been fixed with https://github.com/k2-fsa/k2/pull/226 (Actually a lot of bugs are some boundary cases about TaskRedirect stuffs). Will close this issue.
