### ISSUE TITLE
TopSortHost documentation and return status

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#294]
The documentation of TopSortHost seems to have been copied from TopSort() and doesn't seem to be correct; and the interface for it needs an additional boolean status.
The internal implementation of the host top-sort routine appears to use ConnectCore(), which removes non-accessible and non-co-accessible states.  Therefore if the result has fewer states than the input it does not indicate that there were cycles.
In fact, the host TopSort has no way to indicate an error condition because it produces zero-sized output, which would also be produced if the input was equivalent to the empty FSA.  We need a return status to be passed back (I have also done this for Intersect(); I am about to commit those changes.)

https://github.com/k2-fsa/k2/blob/b9454a315e2ce2ac5d61316e3277794d331e06a1/k2/csrc/fsa_algo.h#L76

**Comment by qindazhu** [comment]
The host version return a boolean value to indicate the fsa has cycles.
https://github.com/k2-fsa/k2/blob/a377250db4b232bd8801c86a2973939325057d6d/k2/csrc/fsa_algo.h#L89-L96

**Comment by danpovey** [comment]
Ah, OK.  We should propagate this to the wrapper in csrc/.

**Comment by qindazhu** [comment]
Aha, I have done this, note the above file I mention is `k2/csrc/fsa_algo.h`. So I guess there's nothing to do about this. (Actually, I have used it for testing GPU TopSort with randomEquivalent, that's why I found that mismatch between the two version. i.e. the host version will `connect` but the GPU version will not.)

Anyway, seems safe to close this issue?

**Comment by danpovey** [comment]
OK.
