### ISSUE TITLE
Implement backprop for log-semiring in Python

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#299]
Is anyone currently doing this task?

**Comment by qindazhu** [comment]
I guess no, you can go forward with this.

**Comment by csukuangfj** [comment]
Ok. Will implement it.

**Comment by danpovey** [comment]
Thanks!
Please give careful thought to how you will cache the various quantities
like the batches, forward-loglikes, backward-loglikes (and remember they
depend on the
semiring).  These things will be needed in backprop and are useful for
multiple separate operations and we don't want to recompute them.

Because the backprop of GetTotalProb() is non-trivial (requires
GetBackwardProbs() which is not necessary for the forward pass) we'll
probably need
a PyTorch Function object.  But I'd rather cache things like the batches
and forward-probs in the Fsa itself, so they can be re-used.
Dan

**Comment by danpovey** [comment]
So I'm thinking the Fsa can have an extra dict, called 'cache' for
instance, that can be used for these kinds of things; we'll have to decide
how to indicate the semiring where appropriate, e.g. by including it in the
name of the key.  And what kind of interface we want for looking up the
forward-loglikes at the Fsa level in Python.

**Comment by danpovey** [comment]
... e.g. one possibility is:

   fsa.GetForwardLoglikes(is_log_semiring: bool)

which would internally access the cache, so the cache would not be exposed
to the user.

**Comment by csukuangfj** [comment]
Resolved by #304 . Closing.
