### ISSUE TITLE
Bugs in RaggedShape2

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#347]
I have been using `RaggedShape2` inside `Union`:
https://github.com/k2-fsa/k2/blob/911a2a93dc2bfa981481001ff58abe918e7c1665/k2/csrc/fsa_algo.cu#L627

But it looks like that `RaggedShape2` does not handle the above calling correctly.

See the code below:

https://github.com/k2-fsa/k2/blob/911a2a93dc2bfa981481001ff58abe918e7c1665/k2/csrc/ragged_ops.cu#L113-L117

`num_rows` is the final state, so the total number of states is `final state + 1`. We should allocate space 
with `final state + 2` elements for `row_splits_array`.

**Comment by danpovey** [comment]
In that case, RaggedShape2() has no way to figure out the number of rows, so it uses the largest of the row-ids plus one.  Since you know that this isn't correct, you need to compute the row-splits yourself by allocating it with the known size, and then calling RowIdsToRowSplits(), before calling RaggedShape2().

**Comment by csukuangfj** [comment]
I will invoke `RowIdsToRowSplits` outside of `RaggedShape2()` with pre-allocated `row_splits_array` instead
of proposing a fix.

Closing.
