### ISSUE TITLE
Make tests run if no GPU available

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#359]
Would be nice to have it so tests can be run (and not crash) when there is no GPU.

(In the longer run we should aim to compile without CUDA as well.)

**Comment by csukuangfj** [comment]
Working on it.

The basic idea is to add a macro `K2_USE_CUDA`.
If it is not defined, `GetCudaContext()` prints an error message and abort the program.
All `GetCudaContext()` calls in tests will be guarded with `K2_CUDA_CUDA`.

**Comment by danpovey** [comment]
Mm, OK.  How would we decide when to set the macro?  I mean, aside from
asking the user to decide?
Presumably we will still require the CUDA toolkit in order to compile.

**Comment by csukuangfj** [comment]
>  How would we decide when to set the macro? 

The macro is set to `OFF` so that GitHub actions can run all of the tests.

It should be set to ON whenever users have a GPU.  We can provide prebuilt wheel packages with `K2_USE_CUDA`
being `ON` and `OFF` and let the user choose which one to download.

PyTorch provides packages that support only CPU:
```
pip install torch==1.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

---

> Presumably we will still require the CUDA toolkit in order to compile.

Yes, the CUDA toolkit is still needed because some code  in `context.h` depends on CUDA, though
it is not required at runtime if `K2_USE_CUDA==OFF`.

**Comment by danpovey** [comment]
Mm.  You know, after thinking about it I'm not a *huge* fan of this whole approach because the original reason was to fix a *runtime* error.  I think it would be better to, if no GPU is present, print a warning (just once!) and return a CPU context.  An issue with this approach is that it makes configuring the project less intuitive.

If we are to mess around with macros, I think we should be removing compile-time support for CUDA as well, although obviously that would be more complicated.

**Comment by csukuangfj** [comment]
ok, will return a cpu context
