### ISSUE TITLE
Control kernel syncing by environment variable

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#449]
Syncing after each kernel will significantly impact the speed, and it's a pain to recompile.
I propose that regardless of whether it's debug or release mode, we control syncing of kernels via an environment
variable K2_SYNC_KERNELS, where if it's defined and nonempty we sync after each kernel call.

**Comment by qindazhu** [comment]
what do you mean `kernel sync` here? Currently the main build speech issue is because we set too many `COMPUTE_ARCHS` in top CMakeList.txt (well, we have to, for compatibility), I change the line `set(K2_COMPUTE_ARCHS 35 50 52 53 60 61 70)` to `set(K2_COMPUTE_ARCHS 70)` locally when build on our CloundML cluster. The build speech is reasonable when I build with `make -j 20`. Maybe @csukuangfj can make more comments about this.

**Comment by danpovey** [comment]
I mean cudaDeviceSynchronize() or whatever we call after each kernel.  Not about build time.I'm talking about the fact that in order to debug certain issues that might occur in release mode, we'd need to rebuild.

**Comment by qindazhu** [comment]
Ah, understand! I'm fine with it. I can do this together with my next PR if there's no other one taking it.

**Comment by danpovey** [comment]
Great!

**Comment by qindazhu** [comment]
Added in https://github.com/k2-fsa/k2/pull/452, closed
