### ISSUE TITLE
Connect() for device

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#761]
We need a Connect() function that will run on device.
After my fix of #760, Connect() on host is by far the limiting factor for LM rescoring speed.

**Comment by pkufool** [comment]
I will do it tomorrow.

**Comment by danpovey** [comment]
Thanks!
It might make sense to do it as a modification or an extension of the top-sorting code.
The top-sorting code should be able to arrange the accessible state (i.e. those accessible from the start state)
in batches, and it should be possible to go in reverse order on those batches to determine which are
co-accessible (i.e. can access the final state).

**Comment by galv** [comment]
What do you need Connect() for? Is intersection creating non-accessible and non-coaccessible states?

**Comment by danpovey** [comment]
Intersection might create non-coaccessible states. yes.

**Comment by galv** [comment]
> and it should be possible to go in reverse order on those batches to determine which are co-accessible 

I'm not sure that this is true. I assume you meant that it is possible to create a breadth-first tree, using the final state as the origin node, and use simply mark the states note in that tree as non-coaccessible. You would build the breadth-first tree by finding the states in batch i-1 that point to the states in batch i that are already known to reach the final state (terminate when i == 1). You initialize the known states that can reach the final state with just the final state itself.

Consider the following:

![image](https://user-images.githubusercontent.com/4767568/122333068-6d857a80-ceec-11eb-9733-6bd9a7412428.png)


Toposort should create three batches, which I've labeled 0, 1, and 2.

Batch 0 contains state S (start state)
Batch 1 contains States A and T (final state).
Batch 2 contains state B.

Essentially, the algorithm would run for only one loop in my case, marking S as coaccessible, but not marking states A or B as coaccessible, because it has no way to discover that A can access T, since B does not appear in Batch 0 (i.e., the batch previous to T's batch). Transitively, A cannot be discovered as coaccessible either. This makes sense, because your "batches" are essentially a representation of a particular depth-first tree (i.e., the depth first tree which corresponds to a toposort).

I might be missing something here, of course. But I feel like an in-place transpose of the graph is more straightforward (on which you then run toposort, swapping the final and start states). In-place transpose should be possible since the backing memory of a Ragged is contiguous IIRC.

**Comment by danpovey** [comment]
Mm but my assumption was that the batches represent a top-sorting, meaning that that no state within a batch j has arcs to any state in  batch <= j.  Of course this is only possible for acyclic FSAs.

**Comment by galv** [comment]
Yes, that makes sense. I was mistaken.

@pkufool I may be able to take on this task if you are busy right now. I need to build more hands-on experience with K2 somehow. Please let me know if you would like that.

**Comment by pkufool** [comment]
@galv It's almost done, will create PR soon.

**Comment by galv** [comment]
@pkufool okay, thank you for confirming.
