### ISSUE TITLE
k2.intersect_dense triggers ValueError: cannot create std::vector larger than max_size()

### ISSUE THREAD

**Issue by GNroy** [k2-fsa/k2#815]
I'm occasionally encountering `ValueError: cannot create std::vector larger than max_size()` when calling `k2.intersect_dense`:
```
File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.3.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/autograd.py", line 550, in forward
    ragged_arc, arc_map_a, arc_map_b = _k2.intersect_dense(
ValueError: cannot create std::vector larger than max_size()
```
I don't think the error is exactly related to an OOM issue: e.g. I'm getting the ValueError with batch size 32 (occupied gpu memory around 50%) and not getting it with batch size 16 (occupied gpu memory around 30%).
Thus there is a possibility that this behavior is some kind of bug. I wonder if anyone else had this?

**Comment by pkufool** [comment]
https://github.com/k2-fsa/k2/blob/818b138b33eabe440601df8910a2b97ac088594b/k2/csrc/intersect_dense.cu#L694-L699

https://github.com/k2-fsa/k2/blob/818b138b33eabe440601df8910a2b97ac088594b/k2/csrc/intersect_dense.cu#L969-L981


I guess it relates to the resizing steps_, we should declare `T_` with `std::vector<Step>::size_type`.

**Comment by pkufool** [comment]
And, what's your cpu memory size, this error may occur when there is no enough contiguous memory to allocate.

**Comment by danpovey** [comment]
T_ relates to the acoustic sequence length, so should never be big enough
to overflow int32.  It does look to me more like a bug.
I think the easiest way to debug it might be to either somehow catch the
exception in gdb, or add a print statement that prints out some info when
T_ is outside a reasonable range, e.g. when T_ + 1 is negative.
It could even be memory corruption, but unfortunately memory corruption is
very hard to detect in Python because valgrind has so many false positives.
I once read of a valgrind extension of some kind that could solve that, but
I was not able to install it.

**Comment by pkufool** [comment]
@GNroy I can't reproduce your error, even with very large graphs, It only cause OOM errors.

Could you please try run you program with gdb and post some logs here. Or, I thought you were using intersect_dense to calculate ctc_loss, could you dump you nnet_output and decoding_graph to *.pt files and upload them somewhere that available to us. Thanks!

**Comment by danpovey** [comment]
I think we need to start relying on the max_states arg of intersect_dense_pruned for the MMI  denominator (assuming
we are using that version of intersection), to prevent OOMs early in training.  E.g. set it to 150 or something like that.

**Comment by GNroy** [comment]
@danpovey, thanks!
The current errors appear when using `k2.intersect_dense`.
I've tried using `k2.intersect_dense_pruned` before (with the default 10000 `max_active_states`) and it gave me the folloving broken OOM:
```
    den_tot_scores = den_lats.get_tot_scores(
  File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/fsa.py", line 695, in get_tot_scores
    tot_scores = k2.autograd._GetTotScoresFunction.apply(
  File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/autograd.py", line 61, in forward
    tot_scores = fsas._get_tot_scores(use_double_scores=use_double_scores,
  File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/fsa.py", line 674, in _get_tot_scores
    forward_scores = self._get_forward_scores(use_double_scores,
  File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/fsa.py", line 624, in _get_forward_scores
    entering_arc_batches=self._get_entering_arc_batches(),
  File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/fsa.py", line 564, in _get_entering_arc_batches
    incoming_arcs=self._get_incoming_arcs(),
  File "/opt/conda/lib/python3.8/site-packages/k2-1.6.dev20210825+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/fsa.py", line 550, in _get_incoming_arcs
    cache[name] = _k2.get_incoming_arcs(self.arcs,
RuntimeError: CUDA out of memory. Tried to allocate 17179869182.06 GiB (GPU 1; 22.16 GiB total capacity; 11.81 GiB already allocated; 6.10 GiB free; 14.73 GiB reserved in total by PyTorch)
```
Thanks to you advice, I set `max_active_states` to 150 and that helped fix the memory consumption issue. However, it remains to be investigated whether composition with such small `max_active_states` affects model convergence.

**Comment by pkufool** [comment]
> P.S. If the `std::bad_alloc` is the int32 issue, can we go to int64? We may want to use very large lattices anyway since there are GPUs like the 80GB A100.

I am trying to use `int64_t`, but I found that we'll need to change a lot of current code, we assumed the dim of `Array` is less than `int32_t`. To support `int64_t`, we have to template `RaggedShape`  to `int64_t` and change all the index argument to something like `size_t`, and also modify the related commonly used functions.
@danpovey What's your advice?

I would add some check first to tell users what happened and how to avoid this issue.

**Comment by danpovey** [comment]
Hm.  It definitely should be possible to modify things so that the metadata (dims) is int64_t.  (We should
avoid unsigned types because it can cause a lot of hard-to-find bugs when things become negative and
are interpreted as very large).  This will require some datatype conversion if, in most cases, we keep the 
actual data (array elements) at int32_t.  However, I'm a little cautious about using Ragged with the metadata
at int64_t at this stage of the project.  Reasons:
   - might significantly increase compilation time (not 100% sure about this).
   - If we have both int32_t and int64_t ragged arrays around, we'll often have to convert one to the other in algorithms.
   - If we change int32_t to int64_t everywhere, it will nearly double the size of all data structures, and have a significant effect on algorithm speed.
If this is happening in things like intersection or other specific algorithms, it's possible to reconfigure or modify these algorithms to avoid the problem by doing things like pruning.  Operating on things like lattices with more than 2^31 states is going to be slow anyway.

**Comment by pkufool** [comment]
Agreed.
There is actually a dynamic beam pruning for states, we may do the similar thing for arcs.

https://github.com/k2-fsa/k2/blob/818b138b33eabe440601df8910a2b97ac088594b/k2/csrc/intersect_dense.cu#L277-L289

**Comment by danpovey** [comment]
Yes, it would be reasonable to reconfigure the limit to be a number of active arcs, rather than states.
Then it would have more reasonable behavior for different sizes of graph.
In fact, it might be easy to just support both limits, at least in the short term, for back compatibility.
(As long as it does not make the implementation significantly more complex).

**Comment by GNroy** [comment]
@pkufool Thanks for your PR!
Can't wait to try it, since I also hit this 15kk limit for states when I train my wordpiece-based MMI models with 3-gram LMs. So I'm planning to try and increase this limit until getting OOMs.

@danpovey Because of the dynamic beam pruning for states in `intersect_dense`, I accidentally discovered that pruning inside of the intersection at the start of the training indeed affect convergence. I observed this when my models diverged with a regular batchsize (say, 32) and converged just fine with a smaller batch (8 or 4). The logs say that there was proportionally more pruning events for the bigger batch launches.

P.S. I'm not sure if this information is relevant to you, but it might be of some help.

**Comment by danpovey** [comment]
I'm not sure how the logs would be saying that?
The max states limitation is per channel/utterance, not globally.
I suspect the convergence issue vs batch size may have been an unrelated
issue.

**Comment by GNroy** [comment]
@danpovey 
My logs are flooded with the following:
```
[I] /workspace/nemo/k2/k2/csrc/intersect_dense.cu:285:k2::FsaVec k2::MultiGraphDenseIntersect::FormatOutput(k2::Array1<int>*, k2::Array1<int>*) Num-states 76775667 exceeds limit 15000000, decreasing beam from 10.000000 to 4.420118
[I] /workspace/nemo/k2/k2/csrc/intersect_dense.cu:285:k2::FsaVec k2::MultiGraphDenseIntersect::FormatOutput(k2::Array1<int>*, k2::Array1<int>*) Num-states 18943159 exceeds limit 15000000, decreasing beam from 4.420118 to 3.315088
```
If I significantly reduce the batchsize, these messages become more rare and the beam decrease does not go under 7.5, so I assumed that this might be related to a possible dependency of number-of-states counter on batchsize.

**Comment by pkufool** [comment]
> I'm not sure how the logs would be saying that? The max states limitation is per channel/utterance, not globally. I suspect the convergence issue vs batch size may have been an unrelated issue.

The max states limitation is globally in `IntersectDense`,  I'm afraid.

**Comment by danpovey** [comment]
OK; I doubt this would cause divergence though.
Perhaps you are summing, not averaging, over the minibatch; and you are using an optimizer like Sgd (vs., say, Adam) that is sensitive to the size of the gradient?

**Comment by GNroy** [comment]
Thanks for your suggestions!
I'm pretty sure I'm averaging over the minibatch, and I'm using Adam with the gradient accumulation from pytorch-lightning (e.g. for batchsize 4, the gradient accumulation is set to 8 to match the batchsize 32 under normal conditions).
It still does not guarantee the exact match in convergence (at least I have no solid confidence that the gradient accumulation does not affect the convergence in any way), but I had no such issues before experimenting with 3-gram LMs. So I'm kind of suspicious about this max states pruning.

**Comment by danpovey** [comment]
You could mess with the max-states limit (it may be in the code) to see if
that makes a difference.
Pruning like that, on the lattice, will affect model quality slightly; but
this pruning should only happen near the start of training, when
the model's output is very flat.
Transformers and conformers are, generally, quite hard to initialize.
That's why we typically use a warm-up scheduler like Noam.
These setups can be sensitive to small differences; it could be the pruning
is just like a small change that tips it over the edge.
