### ISSUE TITLE
[doc] Need to update documentation (about get_tot_scroes() in "Core concepts in k2")

### ISSUE THREAD

**Issue by whsqkaak** [k2-fsa/k2#860]
[https://k2-fsa.github.io/k2/core_concepts/index.html#](https://k2-fsa.github.io/k2/core_concepts/index.html#)

I was following the test codes in this documentation.

There are some parts using `k2.get_tot_scores()` method. 

Like this,

```
import k2
s = '''
0 1 10 0.1
0 2 20 0.2
1 3 -1 0
2 3 -1 0
3
'''
fsa = k2.Fsa.from_str(s)
fsa.draw('fsa2.svg')
fsa = k2.create_fsa_vec([fsa])
total_scores = k2.get_tot_scores(fsa, log_semiring=False, use_double_scores=False)
print(total_scores)
# It prints: tensor([0.2000])
```

I think It must be changed to `k2.Fsa.get_tot_scores()`.

In this example, the line,

`total_scores = k2.get_tot_scores(fsa, log_semiring=False, use_double_scores=False)`

may change to

`total_scores = fsa.get_tot_scroes(log_semiring=False, use_double_scores=False)`

**Comment by csukuangfj** [comment]
Thanks for pointing this out. The documentation has not been updated for quite a long time.
I will update it to match the master branch this week.

**Comment by luomingshuang** [comment]
Maybe I can do it. Maybe it can help me have a deep understanding about k2.

**Comment by luomingshuang** [comment]
@whsqkaak , thanks for your pointing. And I have build a PR #861 for update all the example codes in the docs.

In your example, the line 
`total_scores = k2.get_tot_scores(fsa, log_semiring=False, use_double_scores=False)`
should be changed to 
`total_scores = k2.Fsa.get_tot_scores(fsa, log_semiring=True, use_double_scores=False)`,
instead of `total_scores = fsa.get_tot_scroes(log_semiring=False, use_double_scores=False)`.
![image](https://user-images.githubusercontent.com/37799481/140290751-a17fce00-645a-4a2e-ab7a-21df732c4570.png)

![image](https://user-images.githubusercontent.com/37799481/140290903-506748fc-ead0-4dcb-b0ed-11c9a0b4b76d.png)

**Comment by whsqkaak** [comment]
@luomingshuang, Thanks for your quick reply.

Can i ask you one thing?

![1](https://user-images.githubusercontent.com/17093142/140314395-7d239020-2fdb-4416-aa49-bcc9bf3f386a.png)
![2](https://user-images.githubusercontent.com/17093142/140314396-1c81dddf-1406-4c65-a027-ade27f0773fa.png)

The methods are little different, But the results are same.
Which one would be better?
Is it OK to use anything?

**Comment by csukuangfj** [comment]
`get_tot_scores` is a normal method of the class `k2.Fsa`.
People usually use an instance of `k2.Fsa` to invoke `get_tot_scores`, i.e., use

```
fsa.get_tot_scores()
```

I would recommend you to use `fsa.get_tot_scores()`, not `k2.Fsa.get_tot_scores(fsa)`.

**Comment by whsqkaak** [comment]
@csukuangfj, I got it! Thanks for your quick reply!
